/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
