/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "e305fa806bf098e0b91882204a0fefe94a6fcfc4"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
