/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "cf72c4c4f7db75bc3da689cd76513962d31c7b52"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
