/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "713571f9afcf4b673812cd3b52bb5b17c107038b-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
