/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "5e3098d8fad5b3a6fa9c70d6438f416eec201db7"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
