/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "e74b41c6c84638d5a9ee6d254a715bcd9e17c603-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
